### ISSUE TITLE
Bump python version?

### ISSUE THREAD

**Issue by robmarkcole** [hassio-addons/addon-jupyterlab-lite#121]
# Problem/Motivation
I note this addon is on `python3-dev=3.6.7`. Perhaps we can bump to > 3.7 to be consistent with HA?

**Comment by frenck** [comment]
That would require switching from Ubuntu to something else.
I'll look into switching it to Debian, since we have that available nowadays.

**Comment by frenck** [comment]
Current dev switched to Debian, with Python 3.7
