### ISSUE TITLE
Feature request - add jupyterlab-sql addon

### ISSUE THREAD

**Issue by robmarkcole** [hassio-addons/addon-jupyterlab-lite#122]
# Problem/Motivation
The [jupyterlab-sql](https://github.com/pbugnion/jupyterlab-sql) addon allows easy browsing of database tables, and includes a tool for perfoming sql queries. This is a nice complement to the data detective package and provides a simple way to get started exploring the db via a UI.

<img width="1438" alt="image" src="https://user-images.githubusercontent.com/11855322/72132978-41b9a900-3378-11ea-9757-7b4fe9b34ec7.png">

**Comment by frenck** [comment]
Added to current dev.
