### ISSUE TITLE
FATAL: The configured certfile is not found

### ISSUE THREAD

**Issue by xiaoland** [hassio-addons/addon-jupyterlab-lite#39]
When I run Jupyter-lite on Hassio Add-on. I got an error: FATAL: The configured certfile is not found. 
I don't know what make it happened. Is there missing a file?

**Comment by frenck** [comment]
This mean it cannot find the file configured in the `certfile` option of the add-on.
This happens when you enable SSL on the add-on, which requires SSL certificate files...

If you do not use SSL, consider disabling the SSL option.

**Comment by xiaoland** [comment]
oh~thanks. I fixed this problem now. I shut down the SSL than that i can run it.
But it is let me input password every time I login jupyter-lite
