### ISSUE TITLE
 Could not resolve host: github.com

### ISSUE THREAD

**Issue by sim-san** [hassio-addons/addon-jupyterlab-lite#42]
# Problem/Motivation

Jupyterlab Update => Error

## Actual behavior

Jupyterlab addon stops with this error after update:
fatal: unable to access 'https://github.com/home-assistant/home-assistant-notebooks.git/': Could not resolve host: github.com

## Steps to reproduce

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 

-----------------------------------------------------------
 Hass.io Add-on: JupyterLab Lite
 Create documents containing live code, equations, visualizations, and explanatory text.
-----------------------------------------------------------
 Add-on version: 0.2.0
 You are running the latest version of this add-on.
 System: Raspbian GNU/Linux 9 (stretch)  (armv7 / raspberrypi3)
 Home Assistant version: 0.90.2
 Supervisor version: 150
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in e.g, GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] 10-requirements.sh: executing... 
[cont-init.d] 10-requirements.sh: exited 0.
[cont-init.d] 11-nginx.sh: executing... 
[cont-init.d] 11-nginx.sh: exited 0.
[cont-init.d] 20-notebooks-dir.sh: executing... 
fatal: unable to access 'https://github.com/home-assistant/home-assistant-notebooks.git/': Could not resolve host: github.com
[cont-init.d] 20-notebooks-dir.sh: exited 1.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 

## Proposed changes

- Restart
- Reinstallation

<blockquote><img src="https://avatars1.githubusercontent.com/u/13844975?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/home-assistant/home-assistant-notebooks">home-assistant/home-assistant-notebooks</a></strong></div><div>:notebook: Sample Jupyter Notebooks to explore Home Assistant data - home-assistant/home-assistant-notebooks</div></blockquote>
<blockquote><img src="https://avatars1.githubusercontent.com/u/13844975?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/home-assistant/home-assistant-notebooks">home-assistant/home-assistant-notebooks</a></strong></div><div>:notebook: Sample Jupyter Notebooks to explore Home Assistant data - home-assistant/home-assistant-notebooks</div></blockquote>

**Comment by frenck** [comment]
Seems like your server has DNS issues. The add-on cannot control resolving of hostnames, that is not something I can fix or do something about.
