### ISSUE TITLE
No such image: hassioaddons/jupyterlablite-amd64:latest

### ISSUE THREAD

**Issue by tringler** [hassio-addons/addon-jupyterlab-lite#70]
Hello,

I'm unable to install it on my amd64 platform due to `"No such image: hassioaddons/jupyterlablite-amd64:latest"` -  Is there really no image for that platform available?

Thanks, Thomas

**Comment by frenck** [comment]
Yes, there is, please provide the full logs.

**Comment by tringler** [comment]
Here you go:
```
19-07-22 19:34:22 INFO (SyncWorker_5) [hassio.docker.interface] Update image hassioaddons/jupyterlablite-amd64:None to hassioaddons/jupyterlablite-amd64:0.3.0
19-07-22 19:34:22 INFO (SyncWorker_5) [hassio.docker.interface] Pull image hassioaddons/jupyterlablite-amd64 tag 0.3.0.
19-07-22 19:34:32 ERROR (SyncWorker_5) [hassio.docker.interface] Can't install hassioaddons/jupyterlablite-amd64:0.3.0 -> 404 Client Error: Not Found ("no such image: hassioaddons/jupyterlablite-amd64:0.3.0: No such image: hassioaddons/jupyterlablite-amd64:0.3.0").
```

**Comment by frenck** [comment]
That 404 usually indicates: Not enough disk space to download, unpack & install.
(Yeah, you won't expect a 404, but that is unfortunately how it is with Docker).

**Comment by frenck** [comment]
![image](https://user-images.githubusercontent.com/195327/61659900-f841a880-acc8-11e9-96c6-21ee1ad0eeee.png)

**Comment by tringler** [comment]
Ah Ok - That explains everything! Sorry for bothering and thanks a lot!
