### ISSUE TITLE
!include_dir_named is not supported

### ISSUE THREAD

**Issue by radinsky** [hassio-addons/addon-jupyterlab-lite#9]
Once installed, getting the following error when running a sample notebook:

`!include_dir_named is not supported
`

I'm using in my split configuration packages that configured as following:

`packages:  !include_dir_named ../packages
`

**Comment by frenck** [comment]
This is not a limitation of the add-on, but a limitation of the HASS-Data-Detective, which the add-on uses.

Please file an issue about this on that repository.

Thanks! 👍
